project:
  type: website

website:
  navbar:
    background: primary
    search: false
    right:
      - text: Home
        href: home.qmd
      - text: Work
        href: work.qmd
      - text: Posts
        href: posts/index.qmd
      - text: Personal
        href: personal.qmd
    tools: 
      - icon: github
        href: https://github.com/PaulinaSell

format:
  html:
    theme: 
    - jolla
    - styles.scss
    page-layout: full

execute:
  freeze: auto