project:
  type: website

website:
  navbar:
    background: primary
    search: false
    logo: images/website_logo.png
    right:
      - text: Home
        href: index.qmd
      - text: Work
        href: work.qmd
      - text: Posts
        href: posts/index.qmd
      - text: Personal
        href: personal.qmd
    tools: 
      - icon: github
        href: https://github.com/PaulinaSell
  favicon: images/website_logo.png

format:
  html:
    theme: 
      light: [jolla, styles.scss]
      dark: [jolla, styles-dark.scss]
    page-layout: full
    include-in-header: umami.html
highlight-style: github

execute:
  freeze: auto